- name: Install Docker on Virtual Machines
  hosts: all
  become: true
  tasks:

    - name: Update repositories and install docker
      ansible.builtin.apt:
        pkg:
          - docker.io
          - docker-compose
        update_cache: true

    - name: Enable Docker service
      ansible.builtin.systemd_service:
        name: docker
        enabled: yes
        state: started

    - name: Add user to Docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes
